### ISSUE TITLE
多个tag与category

### ISSUE THREAD

**Issue by huangwb8** [nefu-ljw/python-markdown-to-wordpress#1]
多个tag与category应该要怎么写呢？谢谢！

**Comment by nefu-ljw** [comment]
```python
post_metadata = {
    'category': ['分类1', '分类2'],  # 文章分类
    'tag': ['标签1', '标签2'],  # 文章标签
    'status': 'publish'  # 可选publish发布、draft草稿、private隐私状态
}
```

**Comment by huangwb8** [comment]
刚刚测试了一下，感觉好像没法上传~我挂在国外的VPS，这个有关系吗？但我平时访问网站也没有问题呀(￣△￣；)

**Comment by huangwb8** [comment]
> ```python
> post_metadata = {
>     'category': ['分类1', '分类2'],  # 文章分类
>     'tag': ['标签1', '标签2'],  # 文章标签
>     'status': 'publish'  # 可选publish发布、draft草稿、private隐私状态
> }
> ```
其实我想问的是怎么在marddown文档里用多个分类或标签，因为那里的优先级不是比较高

**Comment by nefu-ljw** [comment]
可以先用`test/test-GetPosts.py`这个文件测试一下，能不能获取到你wordpress上已发布的文章标题；

markdown文件中也是用逗号分隔即可，例如`category: [分类1, 分类2]`

**Comment by huangwb8** [comment]
@nefu-ljw 
成功了！谢谢大佬！可能是因为之前测试时电脑上的v2ray用了全局(～￣▽￣) 想起来马上换回PAC模式。太好了，终于不用一篇篇地粘贴了
