### ISSUE TITLE
关于本项目的一点小建议

### ISSUE THREAD

**Issue by huangwb8** [nefu-ljw/python-markdown-to-wordpress#2]
您好！我用了一小段时间，这里有一些项目开发的建议，看能不能派上用场哈！

1. 将新旧文件区分为两个文件夹管理，比如new和legacy。new文件夹可以放自己新写的文章，upload脚本运行后把文件转移到legacy中。这样每次可以运行同一个命令就实现上传和同步两个功能。当然也可以分开实施。
2. update脚本可以增加一个功能，比如对于最近更新的n个文件自动上传。这个通过检测文件日期和for loop应该可以做到。
3. 用户信息通过外置json文件来实现，然后在python里用专门的包和函数去调用。
4. 希望legacy文件的标签或分类变化时，update也可以同步。
5. 其它：起个正式的名字，搞个license，做大做强(～￣▽￣)～ 

大概是这些，谢谢大佬了！以后有什么建议再提出

**Comment by nefu-ljw** [comment]
好的，感谢你的建议，我有时间会更新这个项目的~

关于2,4点提到的update同步问题，目前的逻辑是update脚本将 与本地markdown文件有相同标题的wordpress文章 强制更新为 本地markdown文件的最新版本（类似于`git push --force`），所以我想着这里是不是让用户手动update好一点。

你说的检测文件日期然后自动更新，可以设计一个定时脚本定时进行update；又或者用类似git的功能：检测哪些文件在上次upload之后又被修改了，本地直接建一个git仓库就行。按照这样的思路，我想**脚本加上git工具的配合**，应该能够实现更好的功能。

还有其他的几点，我会尽量实现的，再次感谢你的建议~

**Comment by huangwb8** [comment]
谢谢大佬！非常期待喔！

**Comment by huangwb8** [comment]
@nefu-ljw 大佬，由于最近我都在写博文，所以等不及你更新了。我自己修改了一些内容，也上传到自己的仓库里，你看看有没有什么提示作用之类的，代码也随便拿去改良吧！我觉得现在这个版本勉强可以用：[https://github.com/huangwb8/m2w](https://github.com/huangwb8/m2w)。我没改核心的东西，都是改一些外围的。
